### ISSUE TITLE
window-covering Sends close when restarting PI

### ISSUE THREAD

**Issue by FamJohansson** [lprhodes/homebridge-broadlink-rm#181]
Hello,
I have a problem that my window-covering is closing when my PI is rebooting. And after the PI has been rebooted and I open the home app is says that the window-covering is open. Actually the window-covering is closed.

Can someone help me with this?

"platforms": [

			{
				"platform": "BroadlinkRM",
				"name": "Broadlink RM",
				"accessories": [
					{
					"name": "Rullgardin Stue",
					"type": "window-covering",
					"persistState": "true",
					"resendHexAfterReload": "false",
					"disableAutomaticOff ": "true",
					"totalDurationOpen": 40,
					"totalDurationClose": 35,
					"data": {

						"open":HERE IS MY HEX-code",
						"close":HERE IS MY HEX-code",
						"stop":HERE IS MY HEX-code"
					}
				},

**Comment by FamJohansson** [comment]
Any idea @lprhodes

**Comment by iandronowicz** [comment]
I’m having the exact same issue with my blinds: randomly (I assume that homebridge restarts or something) the blinds closes, this is a big problem for me since sometimes I have my windows open and the blinds get stucked and really damaged.

**Comment by FamJohansson** [comment]
@iprhodes

**Comment by Cloudore** [comment]
Same problem, weird that the status doesn't update on the home app, the codes just get fired from the broadlink to close all the shades on my plug in

**Comment by Nastras** [comment]
Same Problem here.

**Comment by lprhodes** [comment]
Looking into this at the moment.

This:

```
"resendHexAfterReload": "false",
"disableAutomaticOff ": "true",
```
should be
```
"resendHexAfterReload": false,
"disableAutomaticOff ": true,
```

**Comment by Nastras** [comment]
Hello iprhodes,

great that you still support your plugin after such a long time. Thank you!

What do you mean exactly with your last comment?

**Comment by lprhodes** [comment]
The initial issue showed quotation marks around false, which technically makes it true

i.e.

true = true
"true" = true
"false" = true
false = false

If you're still seeing the issue can you send me your config please @Nastras

**Comment by lprhodes** [comment]
Everything checks out for me so I'm assuming that was the issue (i.e. putting "false" instead of false)

Please re-open the issue if you need.

**Comment by Nastras** [comment]
This is part of my config of a shutter i have persist and resend to false because then the error has not occurred anymore.

{
"name":"Rollo 2 Schlafzimmer",
"type":"window-covering",
"persistState": false,
"resendHexAfterReload": false,
"totalDurationOpen": 26,
"totalDurationClose": 25,
"disableLogs": false,
"host":"192.168.xx.xx",
"data":{
"open"

How must the config now look exactly for it to work?

**Comment by lprhodes** [comment]
As long as resendHexAfterReload is set to false rather than "false" then it won't send any hex when the homebridge reconnects,

**Comment by Nastras** [comment]
ok so everything can stay with me and after the next update it should work?

**Comment by lprhodes** [comment]
It shouldn't need an update

**Comment by Nastras** [comment]
Alright, I'll test it later when I'm back home. Many Thanks!

**Comment by FamJohansson** [comment]
@Nastras 
Any successful update?

**Comment by lprhodes** [comment]
@FamJohansson Your config was definitely wrong. @Nastras may not have been

**Comment by Nastras** [comment]
Hello Luke,

is me again .-)

i wanted to give you a short feedback on this problem.

Unfortunately, it still exists.

After a restart, the shutter go down.

I only activated persist.

{
"name": "Rollo 2 bedrooms",
"Type": "window-covering"
"persistState": true,
"resendHexAfterReload": false,
"totalDurationOpen": 26,
"totalDurationClose": 25,
"disableLogs": false,
"Host": "192.168.xx.xx"
"Data": {
"Open"


In addition, there is still the problem that after closing the shutter a second stop command is sent, which was discussed here.

I have the latest version 2.6.8 installed

**Comment by FamJohansson** [comment]
Same for me.

**Comment by lprhodes** [comment]
@Nastras can you paste your full broadlink plugin config please

**Comment by Nastras** [comment]
No problem. This is my current config, the problem does not occur here.
Only if I activate one of both options resendHexAfterReload or persistState or both together.

`{
"bridge": {
"name": "Homebridge-broadlink-rm",
"username": "CC:22:3D:E3:CE:XX“,
"port": 518XX,
"pin": "XXX-XX-XXX“,
"manufacturer": "",
"model": "",
"serialNumber": "0.4.38"
},

"accessories": [
],

"platforms": [
{
"platform":"BroadlinkRM",
"name":"Broadlink RM",
"hideScanFrequencyButton": false,
"hideLearnButton": false,
"accessories":[
{
"name":"Kerzen Wohnzimmer",
"type":"light",
"persistState": false,
"resendHexAfterReload": false,
"disableLogs": false,
"useLastKnownBrightness": true,
"host":"192.168..",
"data":{
"on": "",
"off":"",
"brightness10": "",
"brightness20": "",
"brightness30": "",
"brightness40": "",
"brightness50": "",
"brightness60": "",
"brightness70": "",
"brightness80": "",
"brightness90": "",
"brightness100": ""
}
},
{
"name":"Ambilight Wohnzimmer",
"type":"switch",
"persistState": false,
"resendHexAfterReload": false,
"disableLogs": false,
"host":"192.168..",
"data":{
"on":"",
"off":""
}
},
{
"name": "Ventilator Schlafzimmer",
"type": "fan",
"persistState": false,
"resendHexAfterReload": false,
"disableLogs": false,
"hideSwingMode": false,
"showRotationDirection": false,
"hideV1Fan": true,
"hideV2Fan": false,
"host":"192.168..",
"data": {
"on":"",
"off":"",
"swingToggle": "",
"fanSpeed10": "",
"fanSpeed50": "",
"fanSpeed100": ""
}
},
{
"name":"Rollo 1 Wohnzimmer",
"type":"window-covering",
"persistState": false,
"resendHexAfterReload": false,
"totalDurationOpen": 29,
"totalDurationClose": 27,
"disableLogs": false, 
"host":"192.168..",
"data":{
"open":"",
"close":"",
"stop":""
}
},
{
"name":"Rollo 2 Wohnzimmer",
"type":"window-covering",
"persistState": false,
"resendHexAfterReload": false,
"totalDurationOpen": 29,
"totalDurationClose": 27,
"disableLogs": false,
"host":"192.168..",
"data":{
"open":"",
"close":"",
"stop":""
}
},
{
"name":"Rollo 3 Wohnzimmer",
"type":"window-covering",
"persistState": false,
"resendHexAfterReload": false,
"totalDurationOpen": 30,
"totalDurationClose": 28,
"disableLogs": false, 
"host":"192.168..",
"data":{
"open":"",
"close":"",
"stop":""
}
},
{
"name":"Rollo 2 Schlafzimmer",
"type":"window-covering",
"persistState": false,
"resendHexAfterReload": false,
"totalDurationOpen": 26,
"totalDurationClose": 25,
"disableLogs": false,
"host":"192.168..",
"data":{
"open":"",
"close":"",
"stop":""
}
},
{
"name":"Markise Balkon",
"type":"window-covering",
"persistState": false,
"resendHexAfterReload": false,
"totalDurationOpen": 43,
"totalDurationClose": 45,
"disableLogs": false,
"host":"192.168..",
"data":{
"close":"",
"open":"",
"stop":""
}
}
]
}
]
}`

**Comment by lprhodes** [comment]
Fixed in v2.7.1

**Comment by Nastras** [comment]
The error seems fixed👍

I have a another question for you.

If resendHexAfterReload true and the window cover really stands at 50% and in homekit 100% then after a restart or reboot the window cover should go to 100%? I just tested it here, nothing happens. Or I still do not quite understand the function 😬

**Comment by lprhodes** [comment]
Fixed that in v2.7.3 just now

**Comment by lprhodes** [comment]
Looks like you have a missing HEX code.

Send over your config

**Comment by FamJohansson** [comment]
Hi,

Here is my Jason file. have taken away other accessories

[config.json.zip](https://github.com/lprhodes/homebridge-broadlink-rm/files/1772139/config.json.zip)

**Comment by FamJohansson** [comment]
@lprhodes
Have you looked into the problem?
