### ISSUE TITLE
How change status of tv using ping..

### ISSUE THREAD

**Issue by felipesalomao** [lprhodes/homebridge-broadlink-rm#293]
Hi, i see that new feature was developed to change status of tv using ping (it knows if tv is on or off)..

I tried: 

```
 {
					"name": "tv quarto",
					"type": "switch",
                                        "allowResend": "true",
                                        "pingIPAddress":"192.168.1.237",                                      
					"data": {
                                        
						"on": "260050000001269414111312123713121212131213121311133713361312123713371336133613371212121313121237131212121312131213361336133713121237133613371237130005210001264a13000d050000000000000000",
						"off": "260050000001269414111312123713121212131213121311133713361312123713371336133613371212121313121237131212121312131213361336133713121237133613371237130005210001264a13000d050000000000000000"
					}

```

Then it started sending command each sencod  to power off and power on tv..
then i tried: 

```
 {
					"name": "tv quarto",
					"type": "switch",
                                        "allowResend": "true",
                                        "pingIPAddress":"192.168.1.237",  
                                        "pingIPAddressStateOnly": "true",                                    
					"data": {
                                        
						"on": "260050000001269414111312123713121212131213121311133713361312123713371336133613371212121313121237131212121312131213361336133713121237133613371237130005210001264a13000d050000000000000000",
						"off": "260050000001269414111312123713121212131213121311133713361312123713371336133613371212121313121237131212121312131213361336133713121237133613371237130005210001264a13000d050000000000000000"
					}

```
instead power off and power on each sencod  i  had this message each sencod (without action).. 
`[2018-3-14 13:51:24] [Broadlink RM] tv quarto getSwitchState: false`

I just would like to sync tv status (on or off).. then if i power on using siri and then power off using my tv remote, homekit will be update and will know that tv is powered off..
I think that is proppose for new feature, right?
Do you know how make it work correctly?

Thank you very much for your time developing great tool..

**Comment by lprhodes** [comment]
If you were getting `tv quarto getSwitchState: false` each second then it means that the IP address could not be reached and so it would show it as turned off.

If it still was showing that when it's turned on then I would guess that either the TV doesn't support being pinged or the IP address is wrong.

**Comment by felipesalomao** [comment]
Me again, sorry.. hahahha

tested it and address can be pinged.. its strange.. 

my conf now: 
```
 {
					"name": "tv quarto",
					"type": "switch",
                                        "pingIPAddress": "192.168.1.237",
                                        "pingFrequency": 2,
                                        "pingIPAddressStateOnly": true,
                                        "allowResend": true,
                                       	"data": {
                                        
						"on": "260050000001269414111312123713121212131213121311133713361312123713371336133613371212121313121237131212121312131213361336133713121237133613371237130005210001264a13000d050000000000000000",
						"off": "260050000001269414111312123713121212131213121311133713361312123713371336133613371212121313121237131212121312131213361336133713121237133613371237130005210001264a13000d050000000000000000"
					}
				},
```

Here my log showing false status  and then after ping sucessfull same address..

```
[2018-3-15 02:09:55] [Broadlink RM] tv quarto getSwitchState: false
[2018-3-15 02:09:57] [Broadlink RM] tv quarto getSwitchState: false
[2018-3-15 02:09:59] [Broadlink RM] tv quarto getSwitchState: false
[2018-3-15 02:10:01] [Broadlink RM] tv quarto getSwitchState: false
[2018-3-15 02:10:03] [Broadlink RM] tv quarto getSwitchState: false
[2018-3-15 02:10:05] [Broadlink RM] tv quarto getSwitchState: false
[2018-3-15 02:10:07] [Broadlink RM] tv quarto getSwitchState: false
[2018-3-15 02:10:09] [Broadlink RM] tv quarto getSwitchState: false
^C[2018-3-15 02:10:10] Got SIGINT, shutting down Homebridge...
root@raspberrypi:~# ping 192.168.1.237
PING 192.168.1.237 (192.168.1.237) 56(84) bytes of data.
64 bytes from 192.168.1.237: icmp_seq=1 ttl=64 time=1.81 ms
64 bytes from 192.168.1.237: icmp_seq=2 ttl=64 time=1.67 ms
64 bytes from 192.168.1.237: icmp_seq=3 ttl=64 time=1.39 ms
64 bytes from 192.168.1.237: icmp_seq=4 ttl=64 time=1.86 ms
64 bytes from 192.168.1.237: icmp_seq=5 ttl=64 time=3.69 ms
64 bytes from 192.168.1.237: icmp_seq=6 ttl=64 time=2.63 ms
64 bytes from 192.168.1.237: icmp_seq=7 ttl=64 time=3.64 ms
^C
--- 192.168.1.237 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6007ms
rtt min/avg/max/mdev = 1.393/2.386/3.692/0.883 ms
root@raspberrypi:~#

```

i just would like to sync tv status (on or off) using this ping feature..

**Comment by lprhodes** [comment]
Fixed in 3.2.14

**Comment by felipesalomao** [comment]
It worked.. You are the best.. fixed a lot of things tonight..

One complex feature that would make it perfect.. 
Have some way to broaddling aways listen hex codes.. if it detect some especific hex to power off ac or  set 19c.. it will see and keep device status sync even you change things with remote.. I know that it would be too complex.. but would make things really smart.. aways devices status in sync.. does not matter if you use remote and homekit at same time..

Thank you a lot!

**Comment by lprhodes** [comment]
Check this out https://github.com/lprhodes/homebridge-broadlink-rm/issues/290

**Comment by shulyaev** [comment]
Hi,
I am running "oznu/homebridge" on Docker (Synology NAS), and still have the same issue in v3.5.5


config.json
```
"platforms": [
        {
            "platform":"BroadlinkRM",
            "name":"Broadlink RM",
            "accessories": [
				{
					"name": "TV",
					"type": "switch",
					"pingIPAddress": "192.168.1.111",
					"pingFrequency": 5,
					"pingIPAddressStateOnly": true,
					"allowResend": true,
					"data": {
						"on": "26005e...",
						"off": "26005e..."
					}
				},
```



>[2018-4-12 10:18:18] [Broadlink RM] TV getSwitchState: false                    
[2018-4-12 10:18:23] [Broadlink RM] TV getSwitchState: false                              
[2018-4-12 10:18:28] [Broadlink RM] TV getSwitchState: false                    
[2018-4-12 10:18:33] [Broadlink RM] TV getSwitchState: false                          
[2018-4-12 10:18:38] [Broadlink RM] TV getSwitchState: false                    



> /homebridge # ping 192.168.1.111                                                
PING 192.168.1.111 (192.168.1.111): 56 data bytes                               
64 bytes from 192.168.1.111: seq=0 ttl=64 time=2.308 ms                         
64 bytes from 192.168.1.111: seq=1 ttl=64 time=2.396 ms                         
64 bytes from 192.168.1.111: seq=2 ttl=64 time=2.318 ms                         
64 bytes from 192.168.1.111: seq=3 ttl=64 time=1.886 ms

**Comment by cubilon** [comment]
try a lowest ping rate, try 60 seconds

**Comment by luvmex** [comment]
The "pingFrequency": 5,  I have already tried for 1, 5, 60, 360 and It's still the Hex Send Error.

And the Home app could still operate the accessories, will just print out the Send Error.

At the same time, everything throws the Broadlink RM device will Send Error (Cause Not Get RM Device) for AC, Fan, and Window-Cover.

But those things become normal when I remove this 3 ping line:
"pingIPAddress": "10.0.1.30",
"pingFrequency": 5,
"pingIPAddressStateOnly": true,

**Comment by ziadsehili** [comment]
does ping by ip adress works woth ac either or no
