### ISSUE TITLE
Switch for Shutter

### ISSUE THREAD

**Issue by SeanJohn888** [lprhodes/homebridge-broadlink-rm#49]
Hi, is it possible for a shutter to create a switch or a special Devise in the Config? 
My radio 433mhz shutter has three commands. Up, Down, and Stop ?

**Comment by webpablo** [comment]
Consider this a +1. Also would be nice if Siri recognized the verb open or close for this type of object. (I.e. garage door, shade, window etc)

**Comment by SeanJohn888** [comment]
An idea would be a switch with slider as with the fan. If I select 10% then start the shutter. The switch should automatically switch off after a programmed time and send the stop command.

Or a normal switch which automatically switches off and sends the stop command when switching off.

**Comment by lprhodes** [comment]
@SeanJohn888 How do you propose you then reverse the shutter?

@webpablo "Close" on window decreases it by 5% rather than setting it to 0% so it wouldn't work well there. Also with shades annoyingly it says "The Shades is open" rather than "The Shades are open" ha

**Comment by lprhodes** [comment]
@SeanJohn888 I don't see how the shades accessory is going to work well with IR. We could use the garage door opener which allows for fully open or fully closed. From what you've send it sounds like you need to be able to repeat the command to continue opening/closing the shades rather than just one command for open and one command for close?

**Comment by lprhodes** [comment]
How about this:

You specify a "percentageChangePerSend". If you were to set the value to 10 then when you set the blinds to 50% it will work out that it's currently at 20% and send the "up" code three times in order to get to 50%.  If you say "Open the blinds" and it's they're currently at zero then it will send the code up code 10 times.

**Comment by SeanJohn888** [comment]
Hey thanks for your answer.

Yes it is a command to open and close one. In addition, I have a button on the remote to stop. Fully open and close goes through a switch. If I want to stop the shutter at 50% I must use an additional switch.

I thought you could measure the times the shutter needs to reach certain positions to select these with a slider. Example switch: IR Start to 50% (time 20 sec) after 20 sec a stop command is sent automatically. I hope you can understand what I mean, unfortunately my English is not so good. Do you speak German?

(You specify a "percentageChangePerSend". If you were to set the value to 10 then when you set the blinds to 50% it will work out that it's currently at 20% and send the "up" code three times in order to get to 50%. If you say "Open the blinds" and it's they're currently at zero then it will send the code up code 10 times.) 

This is also a very good idea!

**Comment by lprhodes** [comment]
Check out [1.3.0](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.3.0) and let me know how it goes!

**Comment by SeanJohn888** [comment]
Thanks for the quick help! Unfortunately, it still does not work properly. I have just tested.

The stop command is missing. The window cover does not stop. When the open or close command is sent, it goes up or down to the end. Is it possible that after each stage a stop command is sent after a certain time?

Exampel:
           "name":"Blind",
          "type":"window-covering",
          "percentageChangePerSend":10,
          "interval": 0.5,
          "data":{
            "open":"2600500000012...",
            -> 2 Sec later a Stop command
            "close":"2600500000012..."
            -> 2 Sec later a Stop command 

If that would go would be really great .-)

**Comment by lprhodes** [comment]
It sounded like you had the option increment a little bit at a time?

Thanks!

Luke

**Comment by SeanJohn888** [comment]
I'm not sure what they mean exactly.

I hope I got it right:

It is possible. You brew some time to adapt it?

**Comment by lprhodes** [comment]
Are you able to press a button and they just open by a small amount?

Thanks!

Luke

**Comment by SeanJohn888** [comment]
No, that's impossible. I have three buttons on the original remote control. One to open one to stop and one to close. When one of the buttons is pressed, the window cover moves up or down until the stop button is pressed.

The example of me above is also not correct, since the window cover stops there after each stage.

I am not at all sure whether it is possible to convert the service in stages.

Do you understand where my problem is? Do you have an idea how to fix it or best to integrate it into homekit?

**Comment by lprhodes** [comment]
Ok got it - I'll have a think

Thanks!

Luke

**Comment by SeanJohn888** [comment]
I would like to thank again for the help. I hope we find another possibility.

**Comment by SeanJohn888** [comment]
Have now long thought. 

I believe with the different stages for the shutter does not work. Even if a stop command is sent afterwards, different times result during the high and the downtime. Or do you have an idea?

Can you add more often a device (shutter) in the several switches can be added. These switches should turn off automatically?

Each shutter would then be a device with three switches.

That would be my view for the best way to use the shutter without stage.

Thank You!

**Comment by lprhodes** [comment]
Hey I've just released [1.3.3](https://github.com/lprhodes/homebridge-broadlink-rm/releases/tag/1.3.3) which among other things includes some new functionality that's relevant to this:

- The ability to create a "switch" accessory that automatically sends an "off" hex code after a specified amount of time.
- The ability to add auto-off commands to the "window-covering" accessory

You now have three options:

- use two "switch" accessories one for open and one for close
- use a "window-covering" accessory and set the "percentageChangePerSend" to 100
- use a "window-covering" accessory and set different "onDurationOpen", "onDurationClose" settings and a "off" hex. Then work out a % for "percentageChangePerSend"

The last one will give you the best result.

**Comment by webpablo** [comment]
👏🏼👏🏼👏🏼👏🏼 
I shall load up tonight and try it out.

**Comment by SeanJohn888** [comment]
That sounds great. I will test it today after work and tell you if it works.

Thank You !!!

**Comment by SeanJohn888** [comment]
Hello Iprhodes, I have tested the last cover in the Config (blind3) now. Unfortunately it does not work properly.

Here my experiences:
1.) If I set the slider from 0 to 50, stop the shutter after the programmed time (onDurationOpen) is however in reality only at 10. The command always goes only to 10 then will stop automatically.
- I think here you need an (onDurationOpen) Time for each stage.
- the programming must recognize that the (onDurationOpen) Time is not always valid when changing from 0 to 50 or 50 to 70.
This is also true for driving in mode.

Example: I have a shutter that takes 45 sec to 100%. These are for each stage of 10% - 100%
4.5sec. If I change from 0% to 10% it takes 4.5 sec and it stops. If I change from 0% to 50% the shutter 22.5 sec drive without stop. The stops automatically but after 4.5 sec.

What I have observed, the slider rounds up or down. When I exit the shutter and is not in the area of ​​the round up. Closes the shutter immediately.

 I think here should be a separation between driving out and driving in.
Extend = round up
Retraction = round down

I hope you understand what I mean and hope the whole thing is not too difficult.

I would be very happy if you have a possibility have still to improve

Until now already a big thank you!

**Comment by lprhodes** [comment]
What I had intended when going from 0 to 50% is for the following

Open for 4.5s (onDurationOpen)
Stop
Wait 0.5s (interval)

Repeat the above 5 times

Is this not what you're seeing?

Thanks!

Luke

**Comment by lprhodes** [comment]
...it already rounds up when opening and rounds down when closing.

If I'm at 20% and move to 22% then it will round up to 30%

If I'm at 30% and move to 28% then it will round down to 20%

**Comment by SeanJohn888** [comment]
The round up and round down works. I have tested it again.

The driving in and driving out is therefore only in single steps? I have thought that synonymous multiple stages are skipped?

**Comment by SeanJohn888** [comment]
I have now tested again. The up and downrounding does not work properly. If I jump to 35% at driving out then it jumps back to 30%.

Two commands are sent, first the driving out and then the driving in command. The shutter then goes back in. Normally it should be
Extend

**Comment by lprhodes** [comment]
Yes in single steps - that way it can also support people who have blinds that pressing open only opens it a little bit and then stops by itself right after they’ve pressed the button.

I’m working on an option to better cater for you and handle setting a new % while an existing one is in process.

**Comment by SeanJohn888** [comment]
Thanks a lot! I look forward to the next version! I think the most 433mhz radio receiver for shutter or blends work like mine. If it works later, a lot of people can use this.

**Comment by lprhodes** [comment]
@SeanJohn888 I've just published 1.3.4, I think this is what you're after. It also now handles changing the % when it's already moving.

**Comment by SeanJohn888** [comment]
Super, I'm curious. Still I can not see the new version at npm -.-

**Comment by lprhodes** [comment]
Sorry I had forgotten to publish to npm - it's there now.

**Comment by SeanJohn888** [comment]
Not bad that you forgot it, in Germany was night and I slept .-)

I have now made a test. It works very well but still not perfect.

I'm still not sure what exactly does not work.

The slider now counted the percent when driving in and out which is very good.

I believe the window cover gets pressed by the slider from 0 - 30% more times the command driving out.

Example:

I push to 30 and the window cover makes short jumps (start - start - start) then it moves fluid motion out.

When I select 0 or 100, the window cover does not always reach the end position. It remains a piece before.

Do you have an idea why that is so?

**Comment by lprhodes** [comment]
The reason for it going in short jumps initially is because the accessory receives multiple values one after another unless you move the slider quickly and then stops so that it can recalculate based on the new position. I’ll add a delay so that it’s less likely to do this.

If it doesn’t reach then end then it’s most likely because of your calculations - try increasing the onDurationOpen slightly?

**Comment by lprhodes** [comment]
Give 1.3.5 a go - that fixes the start/stop start/stop

**Comment by SeanJohn888** [comment]
It works very well now !!! You are really great!!!

Just one thing. Is it possible that no stop is calculated when selecting position 0 and 100? The window cover has an automatic end stop for both positions?

That would be very good if the calculation for the position between 10 and 90 for some reason is no longer true.

**Comment by lprhodes** [comment]
I could but I’d rather get to the bottom of why the calculation isn’t correct - does the calculation in the logs look correct?

**Comment by SeanJohn888** [comment]
The calculation of you is correct and also works.

I have set the interval time larger than the onDurationOpen and closeTime. This is the security that nobody sends a command before the action is completed.

In the homekit app before the end of the interval time can be made a new value without running it.

Then the calculation is no longer correct.

The slider does not have the correct position.

To put the window cover back in start or end position would be very good.

There is no other way to fix the position between slider and window cover.

The windowcover recognizes when it is at the start or end is automatic.

What do you think?

**Comment by lprhodes** [comment]
When you change the value in the Home app while is is opening or closing then it stops, waits a second and then moves from the last calculated % to the new one

So if it's at 0% and we set it to 30% it will go:

1%, 2%, 3%...18%, 19% 20%, 21%

then if we set it to 10% it will calculate that we need to move from 21% to 10%

**Comment by lprhodes** [comment]
Also I've just published 1.3.6 which allows you to optionally remove the following:

percentageChangePerSend
onDurationOpen
onDurationClose

and add these instead:

totalDurationOpen
totalDurationClose

**Comment by SeanJohn888** [comment]
Awesome !!! Now everything works perfectly! Many Thanks!!!

If you did not live on the other end of the earth. Then I would now go with you a drink on my bill .-)

Super cool plugin now! This function can not have any other pluging.

I will tell it in a German Homekit forum that even more people have something of it!

I will test it for the next days.

I tell you if everything still works.

Thanks for your great help and your quick reply!

**Comment by lprhodes** [comment]
Really? Great! Can you send me your config before and after please so I can figure out what the issue is with onDurationOpen

Thanks!

Luke

**Comment by SeanJohn888** [comment]
Sure, of course.

 "name":"Shutter Test",
 "type":"window-covering",
 "percentageChangePerSend":10,
 "interval": 5.5,
 "disableAutomaticOff": false,
 "onDurationOpen": 4.5,
 "onDurationClose": 4.5,
 "hold": true,
 "data":{
 "open":
 "close":
 "off":""

 "name":"Shutter Test",
 "type":"window-covering",
 "percentageChangePerSend":10,
 "interval": 5.5,
 "disableAutomaticOff": false,
 "totalDurationOpen": 45,
 "totalDurationClose": 45,
 "hold": true,
 "data":{
 "open":
 "close“:
 "off":

**Comment by SeanJohn888** [comment]
And error already found?

What I remember it will be two additional slider in homekit now. These were not there at the beginning of our experiments.

These also have no function:

- [Broadlink RM] setTargetVerticalTiltAngle:
- [Broadlink RM] setTargetHorizontalTiltAngle:

Can you remove these at the next update or are needed?

**Comment by SeanJohn888** [comment]
I have something else that I noticed.

If the Pi or homebridge makes a restart, the current status is lost.

If the window cover is on position 50 and a restart is made, the window cover can no longer be controlled (driving in) via homekit.

Homekit thinks that the window cover is in position 0.
 
I think it would be good 0 and 100 without calculation are in this case the window cover in the start position to put.

Or I build an additional switch which brings the window cover to the start position to fix that?

What do you think?

**Comment by lprhodes** [comment]
It's not a fix for the new way of configuring though - the old way needs fixing too.

**Comment by lprhodes** [comment]
I'm not looking to add persistent storage at the time sorry!

**Comment by lprhodes** [comment]
I don't see any issue with it staying there?

**Comment by SeanJohn888** [comment]
I think the problem with the reboot and the status will all have.

When using the original remote control is the problem synonymous.

The slider should simply send at 0 and at 100 the start or stop command no matter where the position of the window cover is.

Without calculation and limitation

**Comment by lprhodes** [comment]
Yeah but only if the home bridge gets restarted - that's not a priority at the moment sorry.

**Comment by SeanJohn888** [comment]
Why it did not go with the old config I can not say. I can test it again tomorrow if you want?

**Comment by SeanJohn888** [comment]
Now I've understood you. No problem. Maybe we can fix the problem later

**Comment by lprhodes** [comment]
FYI "disableAutomaticOff" and "interval" do not get used when "hold" is true

**Comment by lprhodes** [comment]
I just fixed an issue with it showing as "Opening" or "Closing" when complete as it wasn't setting the final "current position" correctly so the target position and current position were different.

Also your config can just look like this (though I thought you said it opened slower than it closes?):

```

        {
          "name":"Shutter Test",
          "type":"window-covering",
          "totalDurationOpen": 45,
          "totalDurationClose": 45,
          "data":{
            "open":"2600500000012...",
            "close":"2600500000012...",
            "off":"2600500000012..."
          }
        }
```

**Comment by SeanJohn888** [comment]
If I adjust the config as here in your example, then the automatic stop and the percentage setting no longer works.

The window cover goes directly to 100% when I set the slider to 10%.

Is it correct that way?

Driving in and out is the same speed and same duration.

**Comment by SeanJohn888** [comment]
The error (showing as "opening" or "closing" when complete as it was not setting the final "current position" correctly so the target position and current position were different.) Is also noticeable to me. Just forgot to tell you. Sorry -.-

**Comment by lprhodes** [comment]
> If I adjust the config as here in your example, then the automatic stop and the percentage setting no longer works.

I just pushed out 1.3.9 which fixes the issue (I had forgotten to change the default of "hold" to true instead of false).

1.3.9 also no longer forces rounding to the nearest 10.

**Comment by lprhodes** [comment]
The reason I removed it allows to simplify the configuration as it was pretty confusing.

**Comment by lprhodes** [comment]
FYI 1.4.0 changes "off" to "stop" in the config and 1.4.1 gets rid of tilt, obstruction and hold characteristics.

**Comment by SeanJohn888** [comment]
> The reason I removed it was to simplify the configuration as it was pretty confusing.

That's a good idea.

I hope only that still everything works further .-)

I will test the new version in the next 2 hours with me and tell you if everything works out.

Now it's still a bit early and the neighbors will get angry -.-

**Comment by SeanJohn888** [comment]
I have tested it now. I could not wait.

I have the config adjusted again and the lines removed.

The window cover does not stop. It goes directly to 100.

Here the Logfile:
Apr 21 05:35:49 raspberrypi homebridge[3044]: [4/21/2017, 5:35:49 AM] [Broadlink RM] Markise Balkon setTargetPosition: currently 8%, moving to 0%
Apr 21 05:35:49 raspberrypi homebridge[3044]: [4/21/2017, 5:35:49 AM] [Broadlink RM] Markise Balkon setTargetPosition: 3.6s (45 / 100 * 8) until auto-stop 1492745749380
Apr 21 05:35:49 raspberrypi homebridge[3044]: [4/21/2017, 5:35:49 AM] [Broadlink RM] Hex sent to Broadlink RM device (192.XXX.X.XX; XX:XX:XX:XX:XX:XX)

**Comment by lprhodes** [comment]
Can you please confirm your config.

**Comment by lprhodes** [comment]
The log shows it moving from 8% to 0%

**Comment by SeanJohn888** [comment]
"name":"Markise Balkon",
 "type":"window-covering",
 "totalDurationOpen": 45,
 "totalDurationClose": 45,
 "data":{
"open":"
 "close":"
 "off":"

**Comment by SeanJohn888** [comment]
Apr 21 07:48:35 raspberrypi homebridge[3434]: [4/21/2017, 7:48:35 AM] [Broadlink RM] Markise Balkon setTargetPosition: currently 0%, moving to 10%
Apr 21 07:48:35 raspberrypi homebridge[3434]: [4/21/2017, 7:48:35 AM] [Broadlink RM] Markise Balkon setTargetPosition: 4.5s (45 / 100 * 10) until auto-stop 1492753715904
Apr 21 07:48:35 raspberrypi homebridge[3434]: [4/21/2017, 7:48:35 AM] [Broadlink RM] Hex sent to Broadlink RM device 
Apr 21 07:48:36 raspberrypi homebridge[3434]: [4/21/2017, 7:48:36 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 1
Apr 21 07:48:36 raspberrypi homebridge[3434]: [4/21/2017, 7:48:36 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 2
Apr 21 07:48:37 raspberrypi homebridge[3434]: [4/21/2017, 7:48:37 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 3
Apr 21 07:48:37 raspberrypi homebridge[3434]: [4/21/2017, 7:48:37 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 4
Apr 21 07:48:38 raspberrypi homebridge[3434]: [4/21/2017, 7:48:38 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 5
Apr 21 07:48:38 raspberrypi homebridge[3434]: [4/21/2017, 7:48:38 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 6
Apr 21 07:48:39 raspberrypi homebridge[3434]: [4/21/2017, 7:48:39 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 7
Apr 21 07:48:39 raspberrypi homebridge[3434]: [4/21/2017, 7:48:39 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 8
Apr 21 07:48:40 raspberrypi homebridge[3434]: [4/21/2017, 7:48:40 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 9
Apr 21 07:48:40 raspberrypi homebridge[3434]: [4/21/2017, 7:48:40 AM] [Broadlink RM] Markise Balkon setPositionState: 2
Apr 21 07:48:40 raspberrypi homebridge[3434]: [4/21/2017, 7:48:40 AM] [Broadlink RM] Markise Balkon setTargetPosition: stop
Apr 21 07:48:40 raspberrypi homebridge[3434]: [4/21/2017, 7:48:40 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 10
Apr 21 07:48:49 raspberrypi homebridge[3434]: [4/21/2017, 7:48:49 AM] [Broadlink RM] Markise Balkon setTargetPosition: 3
Apr 21 07:48:50 raspberrypi homebridge[3434]: [4/21/2017, 7:48:50 AM] [Broadlink RM] Markise Balkon setTargetPosition: 0
Apr 21 07:48:50 raspberrypi homebridge[3434]: [4/21/2017, 7:48:50 AM] [Broadlink RM] Markise Balkon setTargetPosition: 0
Apr 21 07:48:51 raspberrypi homebridge[3434]: [4/21/2017, 7:48:51 AM] [Broadlink RM] Markise Balkon setPositionState: 0
Apr 21 07:48:51 raspberrypi homebridge[3434]: [4/21/2017, 7:48:51 AM] [Broadlink RM] Markise Balkon setTargetPosition: currently 10%, moving to 0%
Apr 21 07:48:51 raspberrypi homebridge[3434]: [4/21/2017, 7:48:51 AM] [Broadlink RM] Markise Balkon setTargetPosition: 4.5s (45 / 100 * 10) until auto-stop 1492753731001
Apr 21 07:48:51 raspberrypi homebridge[3434]: [4/21/2017, 7:48:51 AM] [Broadlink RM] Hex sent to Broadlink RM device
Apr 21 07:48:51 raspberrypi homebridge[3434]: [4/21/2017, 7:48:51 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 9
Apr 21 07:48:51 raspberrypi homebridge[3434]: [4/21/2017, 7:48:51 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 8
Apr 21 07:48:52 raspberrypi homebridge[3434]: [4/21/2017, 7:48:52 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 7
Apr 21 07:48:52 raspberrypi homebridge[3434]: [4/21/2017, 7:48:52 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 6
Apr 21 07:48:53 raspberrypi homebridge[3434]: [4/21/2017, 7:48:53 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 5
Apr 21 07:48:53 raspberrypi homebridge[3434]: [4/21/2017, 7:48:53 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 4
Apr 21 07:48:54 raspberrypi homebridge[3434]: [4/21/2017, 7:48:54 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 3
Apr 21 07:48:54 raspberrypi homebridge[3434]: [4/21/2017, 7:48:54 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 2
Apr 21 07:48:55 raspberrypi homebridge[3434]: [4/21/2017, 7:48:55 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 1
Apr 21 07:48:55 raspberrypi homebridge[3434]: [4/21/2017, 7:48:55 AM] [Broadlink RM] Markise Balkon setPositionState: 2
Apr 21 07:48:55 raspberrypi homebridge[3434]: [4/21/2017, 7:48:55 AM] [Broadlink RM] Markise Balkon setTargetPosition: stop
Apr 21 07:48:55 raspberrypi homebridge[3434]: [4/21/2017, 7:48:55 AM] [Broadlink RM] Markise Balkon setCurrentPosition: 0

**Comment by SeanJohn888** [comment]
I have now tested it again. The windowcover does not stop.

**Comment by lprhodes** [comment]
Looks like you missed this:

> FYI 1.4.0 changes "off" to "stop" in the config

**Comment by SeanJohn888** [comment]
What exactly does that mean? 
Can you if in my config what is missing this adjust and show here?

**Comment by SeanJohn888** [comment]
Now I understand, I try it out now.

**Comment by SeanJohn888** [comment]
Fantastic!!! It works without problems. You are the greatest!

Such a stupid mistake, I have not seen.

2 Questions I still have to you:

1.) Do you build the function in the future at 0 and 100 the command open and close without calculation are sent to correct position errors which come by manual operation or restart of the Pi?

2.) The RF function for the RM3 hub is coming soon?

Thank You again for the great work!

**Comment by SeanJohn888** [comment]
Must the two values ​​with in the config? In the example config it does not?

persistState (required?)

resendHexAfterReload (optional)

**Comment by lprhodes** [comment]
They both say optional in the read me

**Comment by lprhodes** [comment]
> 1.) Do you build the function in the future at 0 and 100 the command open and close without calculation are sent to correct position errors which come by manual operation or restart of the Pi?

No - you can add switches to do this

> 2.) The RF function for the RM3 hub is coming soon?
There should be basic support already as mentioned in https://github.com/lprhodes/homebridge-broadlink-rm/issues/29

**Comment by SeanJohn888** [comment]
Roger that! .-)

> No - you can add switches to do this

That I thought synonymous, the function would have saved a switch. Homebridge can take only 99 devices to my knowledge. I have already 90. Must then use a second Pi in use -.-

If you say it does not go then this is perfectly in order.

You are my hero at the moment!

So many cool things in such a short time. Respect!

**Comment by SeanJohn888** [comment]
I have just tested this feature really great:
-persistState

I have not quite understood what this function is. 
- disableLogs 

Sorry if I sometimes ask too much, that is due to my not so good English.

**Comment by lprhodes** [comment]
You read the release notes?

persistState defaults to true by the way so you don’t need to add it

**Comment by SeanJohn888** [comment]
I have not added it. I've only tested it with a reboot.

**Comment by SeanJohn888** [comment]
🙄Oh no I've always read under commits and under code.
Releas note I did not know. There everything is described. Thanks for the advice.

**Comment by SeanJohn888** [comment]
Hello, I have probably found another error.

If the window cover closes is in the homekit app under the line position window cover is on open.

When opening stands windowcover is close at.

I have already tried the codes to turn open in close but then the direction of the slider no more.

![img_1458](https://cloud.githubusercontent.com/assets/27686185/25303929/f7ba27dc-275c-11e7-95c4-5a14ef415b31.PNG)

Can you fix that?

**Comment by SeanJohn888** [comment]
I have also noticed that the times are interchanged by:

"TotalDurationOpen": 25,
"TotalDurationClose": 28,

I thought the times were up and down the same but my window covers have different times for up and down

The problem belongs together?

**Comment by lprhodes** [comment]
> If the window cover closes is in the homekit app under the line position window cover is on open.

Try out 2.0.5 and let me know how it goes.

> I have also noticed that the times are interchanged by...

Maybe I misunderstood you but I checked and "totalDurationOpen" is definitely being used when calculating the time for opening the window-covers and "totalDurationOpen" is definitely being used when calculating the time for closing it.

You should see the calculation in the log as something similar to "setTargetPosition: 22.05s (45 / 100 * 49) until auto-stop" where 45 is replaced with either "totalDurationOpen" or "totalDurationClose" depending on whether the window-covering is opening or closing.

Can you open future issues as new issues please.

**Comment by SeanJohn888** [comment]
Thank you for the reference I think you have understood me correctly.

Unfortunately, I have not yet come to consider it

But I will still make it and give you a feedback.

**Comment by lprhodes** [comment]
OK - please create a new issue if you need.

It's work checking out the release notes for 2.1.0 as you will probably want to add "resendHexAfterReload" to your window-covering accessories.
