### ISSUE TITLE
Error in 3.6.9

### ISSUE THREAD

**Issue by gerritfries** [lprhodes/homebridge-broadlink-rm#520]
Hey Luke!
Happy New Year! Good to see you again. 
After updating to 3.6.7 earlier this morning your plugin worked as expected. With the last update to version 3.6.9 homebridge crashes at startup with the following error:

`Jan 01 10:36:31 dingleberry homebridge[31477]: [1/1/2020, 10:36:31] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
Jan 01 10:36:31 dingleberry homebridge[31477]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Module._compile (internal/modules/cjs/loader.js:959:30)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Module.load (internal/modules/cjs/loader.js:815:32)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
Jan 01 10:36:31 dingleberry homebridge[31477]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
Jan 01 10:36:31 dingleberry homebridge[31477]: [1/1/2020, 10:36:31] Got SIGTERM, shutting down Homebridge...`

**Comment by dewoert** [comment]
Same here, in the log I also see:
Error: Cannot find module 'chai'

**Comment by gncorbin** [comment]
I ran into this as well. I was able to install the module chai from npm.
`npm install chai`

I am unable to get my broadlink working (haven’t been able to even before the update, but that’s a different can of worms). I hope this helps.

**Comment by marcoschmidt79** [comment]
same problem here

**Comment by marcoschmidt79** [comment]
> I ran into this as well. I was able to install the module chai from npm.
> `npm install chai`
> 
> I am unable to get my broadlink working (haven’t been able to even before the update, but that’s a different can of worms). I hope this helps.

doesnt work

**Comment by iandronowicz** [comment]
Same here, won’t load, “chai” required.

Great to hace you working on this plugin again! I truly think is the best homebridge plugin. 

It would be great yo hace the “loading” all accessories fixed...

**Comment by lprhodes** [comment]
Hey, I've released an update with a fix for chai. I thought I was only using the module for development/tests, sorry.

It's unclear whether they was the cause of your issue though @gerritfries so can you give it a go and let me know please?

**Comment by lprhodes** [comment]
@iandronowicz 

> It would be great to have the “loading” all accessories fixed...

Is there an open issue for this already? I went through 150 or so yesterday to figure out what work needed to be done but I may have missed it.

**Comment by dewoert** [comment]
> Hey, I've released an update with a fix for chai. I thought I was only using the module for development/tests, sorry.
> 
> It's unclear whether they was the cause of your issue though @gerritfries so can you give it a go and let me know please?

For me it's working again. Thanks !

**Comment by onefish2** [comment]
Homebridge is still crashing for me even with your latest commit:

Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by lprhodes** [comment]
@onefish2 can you send over your config please, there's nothing that I can use in that log unfortunately.

**Comment by onefish2** [comment]
I have been using your plugin just fine for the past year or so. After upgrading to 3.6.4 to 3.6.7 and even the newest, I got the above error. Here is my my config for the plugin.

{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "hideWelcomeMessage": true,
            "accessories": [
                {
                    "name": "LR Fan",
                    "type": "fan",
                    "host": "192.168.0.16",
                    "hideRotationDirection": true,
                    "data": {
                        "on": "26002400451b1734181b1833181b181b181a181b1835181c1835181c1834181b181c173418000d0500000000",
                        "off": "26002400441b1833181a1933191a191a181a181b181c181c181c181c181b181b181b181b18000d0500000000",
                        "swingToggle": "26002400451b1734181b1833181b181b181a181b1835181c1835181c1834181b181c173418000d0500000000"
                    }
                },
                {
                    "name": "Playroom Fan",
                    "type": "fan",
                    "host": "192.168.0.17",
                    "hideRotationDirection": true,
                    "data": {
                        "on": [
                            {
                                "data": "26002400431d1736171d1a191934181b181b181b191c191a191b191b181b1a19171c1a3217000d0500000000",
                                "pause": 0.5
                            },
                            {
                                "data": "26004800461a1a331a1a1a191c301a1a1a191a1919341a1a1a33191a1a33191a1a191a191a000cd6491a1a331a1a1a191a321a1a1a191a191a331a1a1a33191a1a331a191a191a191a000d05"
                            }
                        ],
                        "off": "26002400451b1835171d171c1835171c171c171c171e171d171c181c171c171c1835171b18000d0500000000",
                        "swingToggle": "26004800461a1a331a1a1a191c301a1a1a191a1919341a1a1a33191a1a33191a1a191a191a000cd6491a1a331a1a1a191a321a1a1a191a191a331a1a1a33191a1a331a191a191a191a000d05"
                    }
                }
            ]
        },

**Comment by onefish2** [comment]
Sorry. I guess I went from 3.5.5 to 3.6.7

**Comment by lprhodes** [comment]
The config works for me, can you let me know your homebridge and node versions please so that I can mimic?

`homebridge --version`
`node --version`

**Comment by onefish2** [comment]
Homebridge - Version 0.4.50
Node - 10.18.0

**Comment by gerritfries** [comment]
Still got the same error with v3.6.11 (Error: The requested platform 'BroadlinkRM' was not registered by any plugin.)

homebridge@0.4.50
node@12.14.0

config.json:
` 
{
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "accessories": [
                {
                    "name": "Saugroboter An",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 5,
                    "data": {
                        "on": [
                            {
                                "data": "2600d20062621130111010101131110f1130113111301230110f1131101011101010111011101110101011101010111011101010120f11101010113111301110103111301131100003d6626211301110101011301110113012301130122f11101130120f1110101011101110101011101110101011101110101011101110110f113111301110103111301230110003ce6262113011101110103111101031113012301130111010311110101011101010111011101110101011101011101011101011101011101130122f120f11301131113012000d05000000000000",
                                "pause": 1
                            },
                            {
                                "data": "2600d20062621130111010101131110f1130113111301230110f1131101011101010111011101110101011101010111011101010120f11101010113111301110103111301131100003d6626211301110101011301110113012301130122f11101130120f1110101011101110101011101110101011101110101011101110110f113111301110103111301230110003ce6262113011101110103111101031113012301130111010311110101011101010111011101110101011101011101011101011101011101130122f120f11301131113012000d05000000000000"
                            }
                        ]
                    }
                },
                {
                    "name": "Saugroboter Ecken Modus",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 5,
                    "data": {
                        "on": [
                            {
                                "data": "2600d2006361122f120f1110103111101130122f1131110f11101130120f11101010113111301110101011101110110f120f111010101230110f113111301130120f1031120f110003d66262122f120f111010311110113010311230110f11101130111010101110122f1131111010101110110f111011101010111011301110113011301131110f1230110f110003cf62621130120f10111031110f113111301130120f11101031120f1010111011301230110f111011101010111011101010120f1130120f113011311130110f1131111010000d05000000000000",
                                "pause": 1
                            },
                            {
                                "data": "2600d2006361122f120f1110103111101130122f1131110f11101130120f11101010113111301110101011101110110f120f111010101230110f113111301130120f1031120f110003d66262122f120f111010311110113010311230110f11101130111010101110122f1131111010101110110f111011101010111011301110113011301131110f1230110f110003cf62621130120f10111031110f113111301130120f11101031120f1010111011301230110f111011101010111011101010120f1130120f113011311130110f1131111010000d05000000000000"
                            }
                        ]
                    }
                },
                {
                    "name": "Saugroboter Home",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 5,
                    "data": {
                        "on": [
                            {
                                "data": "2600d200626112301010120f1130120f113012301130120f110f120f111010311130122f12301110110f11101010120f120f110f120f122f120f122f120f120f1130122f120f120003d462621130120f11101031120f1031122f12301010120f11101010113110311130123010101110120f101011101110101011101130120f113011101110113011301110110003cf6262122f120f111010311110113011301131101011101110101011311031113011311010120f111010101110110f111011101130111010311110101011311031120f10000d05000000000000",
                                "sendCount": 3,
                                "interval": 3
                            }
                        ]
                    }
                }
            ]
        }
`

I've downgraded to v3.6.7 wich is working fine. Have to go to bed now, though.

**Comment by lprhodes** [comment]
Thanks @gerritfries , so 3.6.7 is working and 3.6.8 does not? Determining which specific version caused the issue for you could be key to determining the problem.

**Comment by lprhodes** [comment]
@onefish2 I suspect you'll also be seeing this error:

> Error: Homebridge plugins that use the "homebridge-easy-platform" library require your node version to be at least the v12.14.0 LTM. Current version: v10.18.0

**Comment by onefish2** [comment]
@lprhodes Yes. I am seeing that as well with your newer updates from the past few days. I am going to try 3.6.7 now. I will report back.

**Comment by onefish2** [comment]
@lprhodes Yes. I am seeing that as well with your newer updates from the past few days. I am going to try 3.6.7 now. I will report back.

**Comment by onefish2** [comment]
@lprhodes Yes. I am seeing that as well with your newer updates from the past few days. I am going to try 3.6.7 now. I will report back.

**Comment by lprhodes** [comment]
The solution here isn't to downgrade home bridge, I'd suggest updating your node to 12.14.0 then downloading 3.6.12 of the plugin which will be available in the next 10 mins

**Comment by lprhodes** [comment]
@gerritfries I believe there's probably another error above the one you pasted, can you send that through pelase?

@onefish2 After updating node you should be able to just use 3.6.11: `npm I homebridge-broadlink-rm@3.6.11`

**Comment by onefish2** [comment]
I have successfully upgraded to Node 12.14.0 and rebuild all of my plugins. I am still getting this error with homebridge-broadlink-rm@3.6.11:

Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**Comment by onefish2** [comment]
I have successfully upgraded to Node 12.14.0 and rebuild all of my plugins. I am still getting this error with homebridge-broadlink-rm@3.6.11:

Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**Comment by onefish2** [comment]
Besides the above error, I am getting this in the logs as well:

ERROR LOADING PLUGIN homebridge-broadlink-rm:
[1/1/2020, 5:52:13 PM] Error: Operation not permitted
    at new Socket (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:147:20)
    at new Session (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:545:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:4:34)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)

I have rolled back to 3.6.7 and its working now.

**Comment by RMCob** [comment]
I also was getting the errors noted above. Rolling back to 3.6.7 resolved the problem for me too.

**Comment by lprhodes** [comment]
I'll look into other solutions but in the meantime the following should do the trick assuming node is located at `/usr/bin/node`:

`sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip /usr/bin/node`

(from https://github.com/nospaceships/node-raw-socket/issues/53)

**Comment by lprhodes** [comment]
or a simpler one: `sudo setcap cap_net_raw+ep /path/to/bin/node`

Based on this: https://github.com/nospaceships/node-net-ping/issues/32

**Comment by onefish2** [comment]
@lprohodes I preformed the above command and the updated to 3.6.11. Looks like everything is working now. Thank you for all the back and forth tonight. I am glad to see you are back working on this plugin again. 

Thanks again!!

-Steve

**Comment by lprhodes** [comment]
Awesome, I'm glad it worked. Which one did you use in the end?

**Comment by onefish2** [comment]
I used this command:

sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip /usr/bin/node

**Comment by gerritfries** [comment]
Using the command 
`sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip /usr/local/bin/node`
did the trick for me as well. Now 3.6.11 works like a charm.

Thanks for your help!

**Comment by Reddyzinho** [comment]
nop, doesnt work for me ......and the node is there (i guess).

here is the error: 

Failed to set capabilities on file `/usr/bin/node' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

**Comment by kiwi-cam** [comment]
I had that too. My node executable is a symlink so failed with this error too. Try running `ln -al /usr/bin/node` to identify where the link points and re-run the command using that path.

**Comment by JohnfKamp** [comment]
I run homebridge on a mac, and setcap does not work on a mac. Any idea ?

**Comment by thesquaremedia** [comment]
on Mac as well looking for Mac solution
