### ISSUE TITLE
v3.6.20 - Could not install from "../../usr/local/lib/node_modules/homebridge-platform-helper" as it does not contain a package.json file

### ISSUE THREAD

**Issue by DJay-X** [lprhodes/homebridge-broadlink-rm#538]
```
pi@raspberrypi-3BPlus:~ $ sudo npm install -g homebridge-broadlink-rm
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../usr/local/lib/node_modules/homebridge-platform-helper" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T12_43_09_141Z-debug.log
pi@raspberrypi-3BPlus:~ $ node -v
v12.14.1
pi@raspberrypi-3BPlus:~ $ npm -v
6.13.6
```

[2020-01-16T12_39_32_062Z-debug.log](https://github.com/lprhodes/homebridge-broadlink-rm/files/4071204/2020-01-16T12_39_32_062Z-debug.log)

**Comment by Snoomy** [comment]
sudo npm install -g homebridge-platform-helper

**Comment by pax0707** [comment]
```
pi@raspi:~ $ sudo npm install -g homebridge-platform-helper
+ homebridge-platform-helper@1.2.1
updated 1 package in 5.747s
pi@raspi:~ $ sudo npm install -g homebridge-broadlink-rm
npm ERR! code ENOPACKAGEJSON
npm ERR! syscall open
npm ERR! path /home/homebridge-platform-helper/package.json
npm ERR! errno -2
npm ERR! package.json ENOENT: no such file or directory, open '/home/homebridge-platform-helper/package.json'
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T19_34_58_687Z-debug.log
pi@raspi:~ $ 
```

**Comment by lprhodes** [comment]
Sorry I thought I'd saved a file before committing and I guess I hadn't. 3.6.21 should fix the issue.

**Comment by Snoomy** [comment]
maybe I'm doing something wrong?...

[1/16/2020, 11:20:42 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[1/16/2020, 11:20:42 PM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[1/16/2020, 11:20:42 PM] Loading 0 accessories...
(node:1632) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
(node:1632) UnhandledPromiseRejectionWarning: ReferenceError: ervice is not defined
    at serviceType (/Users/Snoomy/node_modules/homebridge-broadlink-rm/accessories/windowCovering.js:9:20)
    at WindowCoveringAccessory.createServiceManager (/Users/Snoomy/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js:53:51)
    at new HomebridgeAccessory (/Users/Snoomy/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js:42:36)
    at new BroadlinkRMAccessory (/Users/Snoomy/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at new WindowCoveringAccessory (/Users/Snoomy/node_modules/homebridge-broadlink-rm/accessories/windowCovering.js:7:1)
    at config.accessories.forEach (/Users/Snoomy/node_modules/homebridge-broadlink-rm/platform.js:71:32)
    at Array.forEach (<anonymous>:null:null)
    at BroadlinkRMPlatform.addAccessories (/Users/Snoomy/node_modules/homebridge-broadlink-rm/platform.js:63:24)
    at BroadlinkRMPlatform.accessories (/Users/Snoomy/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/platform.js:28:20)
    at Server._loadPlatformAccessories (/Users/Snoomy/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/Users/Snoomy/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/Users/Snoomy/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/Users/Snoomy/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/Users/Snoomy/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

(node:1632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/16/2020, 11:20:42 PM] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro (27c3) at 10.0.0.33 (77:0f:78:4d:f8:70)
[1/16/2020, 11:20:43 PM] [Broadlink RM] 
[1/16/2020, 11:20:43 PM] [Broadlink RM] **************************************************************************************************************
[1/16/2020, 11:20:43 PM] [Broadlink RM] ** Welcome to version 3.6.21 of the Homebridge Broadlink RM Plugin!
[1/16/2020, 11:20:43 PM] [Broadlink RM] **

**Comment by lprhodes** [comment]
Also I would not suggest installing home ridge-platform-helper separately as version conflicts could arise. This plugin is dependant on a feature branch version of platform-helper at the moment

**Comment by DJay-X** [comment]
Thanks for your fast reply @lprhodes 

Unfortunately after trying to update the following issues and homebridge crash.

```
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: [2020-1-16 23:02:14] ERROR LOADING PLUGIN homebridge-broadlink-rm:
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: [2020-1-16 23:02:14] Error: Cannot find module 'hap-nodejs'
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: Require stack:
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/index.js
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge-broadlink-rm/index.js
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge/lib/plugin.js
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge/lib/server.js
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge/lib/cli.js
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]: - /usr/local/lib/node_modules/homebridge/bin/homebridge
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Module.require (internal/modules/cjs/loader.js:848:19)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at require (internal/modules/cjs/helpers.js:74:18)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js:13:22)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Module.load (internal/modules/cjs/loader.js:811:32)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
Jan 16 23:02:14 raspberrypi-3BPlus homebridge[489]:     at Module.require (internal/modules/cjs/loader.js:848:19)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]: [2020-1-16 23:02:36] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Module.load (internal/modules/cjs/loader.js:811:32)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
Jan 16 23:02:36 raspberrypi-3BPlus homebridge[489]:     at internal/main/run_main_module.js:17:11
```

Regular install didn't work due to permission problem. 
Trying --unsafe-perm. Didn't work as well. Homebridge still crash.

```
pi@raspberrypi-3BPlus:~ $ sudo npm install -g homebridge-broadlink-rm

> raw-socket@1.7.0 install /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.14.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build'
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raw-socket@1.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T21_59_41_432Z-debug.log
pi@raspberrypi-3BPlus:~ $ sudo npm install -g --unsafe-perm homebridge-broadlink-rm

> raw-socket@1.7.0 install /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
> node-gyp rebuild

make: Verzeichnis „/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build“ wird betreten
  CXX(target) Release/obj.target/raw/src/raw.o
  SOLINK_MODULE(target) Release/obj.target/raw.node
  COPY Release/raw.node
make: Verzeichnis „/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build“ wird verlassen
+ homebridge-broadlink-rm@3.6.22
added 136 packages from 162 contributors in 73.775s
```

Had to roll back to v3.6.18 but still crash. 
Deleting cachedAccessories fixed it to run with v3.6.18 again.

```
pi@raspberrypi-3BPlus:~ $ sudo npm install -g --unsafe-perm homebridge-broadlink-rm@3.6.18

> raw-socket@1.7.0 install /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
> node-gyp rebuild

make: Verzeichnis „/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build“ wird betreten
  CXX(target) Release/obj.target/raw/src/raw.o
  SOLINK_MODULE(target) Release/obj.target/raw.node
  COPY Release/raw.node
make: Verzeichnis „/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build“ wird verlassen
+ homebridge-broadlink-rm@3.6.18
added 134 packages from 117 contributors in 52.017s
```

**Comment by pax0707** [comment]
Same.
Had to roll back.

**Comment by DJay-X** [comment]
https://github.com/lprhodes/homebridge-broadlink-rm/issues/540

**Comment by wylosmond** [comment]
is my problem the same? if yes how could I opt for different version of the plugin?

My environment: Synology DSM - Docker
Image/Container:  oznu/homebridge
plugin i used (on 29Jan2020): 
npm install -g homebridge-broadlink-rm

**After i put the following in the config.json**

>    "platforms": [
	{
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "hideScanFrequencyButton": false,
      "hideLearnButton": false,
      "hideWelcomeMessage": false,
      "accessories":[]
    }
]

**the LOG return the followings:**


[1/30/2020, 3:07:36 PM] Got SIGTERM, shutting down Homebridge...
-U /homebridge -P /homebridge/node_modules -C
[1/30/2020, 3:07:43 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/30/2020, 3:07:43 PM] ---
[1/30/2020, 3:07:43 PM] Loaded plugin: homebridge-dummy
[1/30/2020, 3:07:43 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[1/30/2020, 3:07:43 PM] ---
[1/30/2020, 3:07:43 PM] ====================
[1/30/2020, 3:07:43 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[1/30/2020, 3:07:43 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js
- /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/index.js
- /usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js
- /usr/local/lib/node_modules/homebridge-broadlink-rm/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
[1/30/2020, 3:07:43 PM] ====================
[1/30/2020, 3:07:43 PM] Loaded plugin: homebridge-config-ui-x
[1/30/2020, 3:07:43 PM] Registering platform 'homebridge-config-ui-x.config'
[1/30/2020, 3:07:43 PM] ---
[1/30/2020, 3:07:43 PM] Loaded plugin: homebridge-webos-tv
[1/30/2020, 3:07:43 PM] Registering accessory 'homebridge-webos-tv.webostv'
[1/30/2020, 3:07:43 PM] ---
[1/30/2020, 3:07:43 PM] Loading 1 platforms...
[1/30/2020, 3:07:43 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[1/30/2020, 3:07:43 PM] Got SIGTERM, shutting down Homebridge...


**P.S. It works perfectly when I only use the webOStv plugin without BroadlinkRM**

before and after the usage of BroadlinkRM platform, the control of TV is perfectly fine. Tested for 2 to 3 times.

**Comment by wylosmond** [comment]
oh, the solution from #540 have helped me.
>install hap-nodejs manually by this line:
> npm install -g --unsafe-perm hap-nodejs@latest
